# Default values for onos-topo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
restartPolicy: Never

image:
  repository: onosproject/onos-topo
  tag: latest
  pullPolicy: IfNotPresent
  pullSecrets: []

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

debug: false

namespace: default

store:
  enabled: false
  namespace: default
  raftgroup: raft
  controller: atomix-controller.default.svc.cluster.local:5679
  raft:
    partitions: 1
    partitionSize: 1

ingress:
  enabled: false

resources: {}

service:
  type: ClusterIP

nodeSelector: {}

tolerations: []

affinity: {}
