apiVersion: v1
appVersion: "1.0"
description: ONOS Topology service
name: onos-topo
version: 0.0.1
kubeVersion: ">=1.12.0"
keywords:
  - onos
  - sdn
home: https://onosproject.org
maintainers:
  - name: Andrea Campanella
    email: andrea@opennetworking.org
  - name: kuujo
    email: jordan@opennetworking.org